env:
  es2020: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  no-bitwise: off
  object-curly-newline: ["error", {"ObjectPattern": { "multiline": true }}]
